## Problem 2: Create buffers around shopping centers (3 points)

Let’s continue with our case study and calculate a 1.5 km buffer around the geocoded points.

### a) Load the shopping centre data set (1 point)

First, load the shopping centre *point* data set you created in *problem 1* into a `GeoDataFrame` called `shopping_centres`.

In [1]:
import geopandas

shopping_centres = geopandas.read_file("data/shopping_centres.gpkg", layer="shopping_centres")
shopping_centres.head()

,address,id,name,addr,geometry
0,"Kauppakeskus Itis, 1-7, Itäkatu, Itäkeskus, Va...",1,Itis,"Itäkatu 1-7, 00930 Helsinki, Finlandia",POINT (25.083 60.212)
1,"Plants By Us, 14-20, Mannerheimintie, Keskusta...",2,Forum,"Mannerheimintie 14–20, 00100 Helsinki, Finlandia",POINT (24.938 60.169)
2,"Elixia Iso Omena, 11, Piispansilta, Matinkylän...",3,Iso-omena,"Piispansilta 11, 02230 Espoo, Finlandia",POINT (24.736 60.162)
3,"Sellon Vapaa-ajankeskus, 3-9, Leppävaarankatu,...",4,Sello,"Leppävaarankatu 3-9, 02600 Espoo, Finlandia",POINT (24.808 60.218)
4,"Stockmann, 3, Vantaanportinkatu, Vantaanportti...",5,Jumbo,"Vantaanportinkatu 3, 01510 Vantaa, Finlandia",POINT (24.963 60.292)


---

### b) Create a *buffer* around the points (1 points)

Calculate a 1.5 km buffer for each geocoded point. Overwrite the `geometry` column with the new buffer geometry.

Use the [`geopandas.GeoDataFrame.buffer()` method](http://geopandas.org/geometric_manipulations.html#GeoSeries.buffer), that uses shapely’s [`buffer()`](http://toblerity.org/shapely/manual.html#object.buffer) in the background. You only need to care about the `distance` parameter, don’t worry about the possible other arguments.

In [4]:
# ADD YOUR OWN CODE HERE
shopping_centres["geometry"] = shopping_centres.buffer(1500)
shopping_centres.head(5)

,address,id,name,addr,geometry
0,"Kauppakeskus Itis, 1-7, Itäkatu, Itäkeskus, Va...",1,Itis,"Itäkatu 1-7, 00930 Helsinki, Finlandia","POLYGON ((1533.765 134.255, 1533.876 131.957, ..."
1,"Plants By Us, 14-20, Mannerheimintie, Keskusta...",2,Forum,"Mannerheimintie 14–20, 00100 Helsinki, Finlandia","POLYGON ((1533.62 134.212, 1533.731 131.914, 1..."
2,"Elixia Iso Omena, 11, Piispansilta, Matinkylän...",3,Iso-omena,"Piispansilta 11, 02230 Espoo, Finlandia","POLYGON ((1533.419 134.205, 1533.53 131.907, 1..."
3,"Sellon Vapaa-ajankeskus, 3-9, Leppävaarankatu,...",4,Sello,"Leppävaarankatu 3-9, 02600 Espoo, Finlandia","POLYGON ((1533.491 134.261, 1533.602 131.963, ..."
4,"Stockmann, 3, Vantaanportinkatu, Vantaanportti...",5,Jumbo,"Vantaanportinkatu 3, 01510 Vantaa, Finlandia","POLYGON ((1533.645 134.336, 1533.756 132.037, ..."

In [5]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
assert shopping_centres.geometry.geom_type.unique() == ["Polygon"]


---

### d) Save buffer geometry layer (1 point)

Save the data frame containing the buffer geometries into a new layer `buffers` inside the same *GeoPackage* `shopping_centres.gpkg`:

In [6]:
shopping_centres.to_file("data/shopping_centres.gpkg", layer="buffers", driver="GPKG")