## Problem 1: Geocode shopping centers (7 points)

The overall aim of problems 1-3 is to find out **how many people live within a walking distance (1.5 km) from certain shopping centres in Helsinki**.

Problem 1 concerns the locations of shopping centres: find their addresses and translate them into coordinates.

---

### a) Prepare an input file containing the addresses of shopping centres (2 point)

Find out the addresses of the following shopping centres (e.g., by using your favourite search engine), and collect them in a text file called `shopping_centres.txt`:

 - Itis
 - Forum
 - Iso-omena
 - Sello
 - Jumbo
 - REDI
 - Tripla 
 
The text file should be in semicolon-separated format (`;`) and include the following columns:

- `id` (integer) a unique identifier for each shopping centre (a
- `name` (string) of each shopping center
- `addr` (string) the address 


See an example of how to format the text file [in the lesson 3 materials](https://autogis-site.readthedocs.io/en/latest/lessons/lesson-3/geocoding-in-geopandas.html). Remember to *add*, *commit*, and *push* the file to your git repository.

---

### b) Read the list of addresses (1 point)

Read the list of addresses you just prepared into a `pandas.DataFrame` called `shopping_centres`

In [4]:
import pandas as pd

shopping_centres = pd.read_csv(
    'data/shopping_centres.txt',
    sep=';',
    header=None,
    names=['id', 'name', 'addr'],
)
shopping_centres.head(5)

   id       name                                              addr
0   1       Itis            Itäkatu 1-7, 00930 Helsinki, Finlandia
1   2      Forum  Mannerheimintie 14–20, 00100 Helsinki, Finlandia
2   3  Iso-omena           Piispansilta 11, 02230 Espoo, Finlandia
3   4      Sello       Leppävaarankatu 3-9, 02600 Espoo, Finlandia
4   5      Jumbo      Vantaanportinkatu 3, 01510 Vantaa, Finlandia

In [5]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
import pandas
assert isinstance(shopping_centres, pandas.DataFrame)
for column in ("id", "name", "addr"):
    assert column in shopping_centres.columns


---

### c) Geocode the addresses (3 points)

Geocode the addresses using the Nominatim geocoding service. Join the results with the input data, and store them in a `geopandas.GeoDataFrame` with the same name (`shopping_centres`). 

Remember to define a custom `user_agent` string!

In [10]:
# ADD YOUR OWN CODE HERE
import geopandas

shopping_centres = shopping_centres.drop(columns=["geometry", "address"], errors="ignore")

geocoded_addresses = geopandas.tools.geocode(
    shopping_centres["addr"],
    provider="nominatim",
    user_agent="autogis2023",
    timeout=10
)

shopping_centres = geocoded_addresses.join(shopping_centres)
shopping_centres.head(5)

,geometry,address,id,name,addr
0,POINT (25.08294 60.21171),"Kauppakeskus Itis, 1-7, Itäkatu, Itäkeskus, Va...",1,Itis,"Itäkatu 1-7, 00930 Helsinki, Finlandia"
1,POINT (24.93781 60.16903),"Plants By Us, 14-20, Mannerheimintie, Keskusta...",2,Forum,"Mannerheimintie 14–20, 00100 Helsinki, Finlandia"
2,POINT (24.73629 60.16213),"Elixia Iso Omena, 11, Piispansilta, Matinkylän...",3,Iso-omena,"Piispansilta 11, 02230 Espoo, Finlandia"
3,POINT (24.80836 60.21818),"Sellon Vapaa-ajankeskus, 3-9, Leppävaarankatu,...",4,Sello,"Leppävaarankatu 3-9, 02600 Espoo, Finlandia"
4,POINT (24.96282 60.29245),"Stockmann, 3, Vantaanportinkatu, Vantaanportti...",5,Jumbo,"Vantaanportinkatu 3, 01510 Vantaa, Finlandia"

In [11]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
import geopandas
assert isinstance(shopping_centres, geopandas.GeoDataFrame)
for column in ("id", "name", "addr", "geometry"):
    assert column in shopping_centres.columns

Check that the coordinate reference system of the geocoded result is correctly defined, and **reproject the layer into ETRS GK-25** (EPSG:3879):

In [19]:
# ADD YOUR OWN CODE HERE
print(shopping_centres.crs)  # geocoding returns EPSG:4326 (lon/lat)
shopping_centres = shopping_centres.to_crs("EPSG:3879")

In [20]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
import pyproj
assert shopping_centres.crs == pyproj.CRS("EPSG:3879")


---

### d) Save the resulting vector data set (1 point)

Save `shopping_centres` as a *GeoPackage* named `shopping_centres.gpkg`:

In [21]:
# ADD YOUR OWN CODE HERE
shopping_centres.to_file("data/shopping_centres.gpkg", layer="shopping_centres", driver="GPKG")


---

Well done! Now you can continue to [problem 2](Exercise-3-Problem-2.ipynb)